DI-254 Adds placeholder methods and classes for endpoint routing. Creates buils-test gh workflow
Nayya-com/data-infra-consent-capture pull request #3
Opened 2024-05-17 23:51 UTC by CamiloEVelasco

> **_SHIPPED NOTE:_**  Adds placeholder methods and classes for endpoint routing. Creates buils-test gh workflow in data-infra consent capture.

NOTE: Hi there Avi, I know this was supposed to be only the creation of the github workflow but while doing that I found out I needed the database to be instanced, which in order required the app creation script to exist and... let's just say I got a bit carried away. Most of the stuff I've added here is a foundation upon which we can start building the stuff that's already detailed in the existing tickets, as well as some placeholder values that we can later modify as needed.

## As the author of this PR, I have:

- [ ] Manually tested my proposed changes and verified that there were no server errors or UI bugs
- [ ] Written a summary of the proposed changes as a PR comment and how to test them, if applicable ([example](https://github.com/Nayya-com/nayya-insurance/pull/327))
- [ ] If applicable, I have added documentation in [notion](https://www.notion.so/Product-and-Engineering-e965393fa4154611b4b008d9adb08e86) describing how the feature works
- [ ] Confirmed that automated tests are passing
- [ ] Assigned one or more [reviewers](https://www.notion.so/Code-Reviews-0c16b837cc4b418c904ed39691c193fe#2e862cf919f14c95937e4d373f218ad6)

2024-05-20 23:04 UTC, aviral-nayya commented on tests/conftest.py
Where was this adapted from? Is this certain to work?

2024-05-21 20:14 UTC, jordan-clarkyy commented on .github/workflows/build-test.yml
> +        image: postgres:12
can we use postgres 16?

2024-05-21 20:14 UTC, jordan-clarkyy commented on .github/workflows/build-test.yml
> +        run: sudo apt-get update
like the other PR, dont think this is needed

2024-05-21 20:14 UTC, jordan-clarkyy commented on app/config.py
> +    CMK: str = os.getenv("CMK", "FAKE_CMK")
is all of this config needed rn?

2024-05-21 20:14 UTC, jordan-clarkyy commented on app/factories/fastapi_instance.py
> +    def receive_do_connect(
how does this work with the DB session management?

2024-05-21 21:26 UTC, CamiloEVelasco commented on app/config.py
> +    CMK: str = os.getenv("CMK", "FAKE_CMK")
Nope, just some placeholders for stuff we might use down the line

2024-05-21 21:35 UTC, aviral-nayya commented on .github/workflows/build-test.yml
> +        image: postgres:12
Have you been using postgres 16 for opportunities?

2024-05-21 21:38 UTC, jordan-clarkyy commented on .github/workflows/build-test.yml
> +        image: postgres:12
Yup

2024-05-21 22:01 UTC, aviral-nayya commented on app/config.py
> +    CLIENT_SIDE_JWT_VERIFY: bool = os.getenv("CLIENT_SIDE_JWT_VERIFY", "false").lower() == "true"
Are we using JWT auth? Why can't we just be in the same VPC?

2024-05-21 22:02 UTC, aviral-nayya commented on app/config.py
> +    EXPOSE_TEST_UI: bool = False
Where's this EXPOSE_TEST_UI coming from? Is there a recipe that you've been following that I can reference?

2024-05-21 22:07 UTC, CamiloEVelasco commented on app/config.py
> +    EXPOSE_TEST_UI: bool = False
It depends on the env, tends to be False in production and True for other envs

2024-05-21 22:07 UTC, CamiloEVelasco commented on app/config.py
> +    CLIENT_SIDE_JWT_VERIFY: bool = os.getenv("CLIENT_SIDE_JWT_VERIFY", "false").lower() == "true"
All of these are placeholders to be modified as needed. I'll remove the unnecessary ones for now

2024-05-21 22:08 UTC, aviral-nayya commented on app/config.py
> +    EXPOSE_TEST_UI: bool = False
How is this meant to be used?

2024-05-21 22:08 UTC, aviral-nayya commented on app/db.py
> +        raise ValueError("Database URL not found")
I assume this is subject to change pending a decision on the sync vs async session pattern?

2024-05-21 22:10 UTC, CamiloEVelasco commented on app/factories/fastapi_instance.py
> +    def receive_do_connect(
I think since it works by listening to the engine and not to a particular session it's not affected by it

2024-05-21 22:14 UTC, CamiloEVelasco commented on requirements/dev.txt
> +flower
Good catch

2024-05-21 22:15 UTC, CamiloEVelasco commented on app/db.py
> +        raise ValueError("Database URL not found")
In either case no engine can be created if the url is missing, so I think this behavior would stay regardless

2024-05-21 22:17 UTC, aviral-nayya commented on app/factories/fastapi_instance.py
> +    def receive_do_connect(
+1 to the above question, also not able to figure out why this exists.

2024-05-21 22:31 UTC, aviral-nayya commented on tests/conftest.py
> +    def restart_savepoint(sess2: Session, trans: Transaction) -> None:
Should we have unit tests for testing utilities lol?

2024-05-21 22:38 UTC, aviral-nayya commented on app/utils/exception_handling.py
> +def configure_exception_handlers(app: FastAPI) -> None:
I know we don't have any endpoints, but is there a way to write tests against this?

2024-05-21 22:38 UTC, aviral-nayya requested changes
A few changes I'd recommend

2024-05-21 22:41 UTC, CamiloEVelasco commented on app/config.py
> +    EXPOSE_TEST_UI: bool = False
It exposes the UI at `localhost:5000` for easy debugging/testing new features

2024-05-21 23:27 UTC, CamiloEVelasco commented on app/factories/fastapi_instance.py
> +    def receive_do_connect(
It was used to dynamically refresh rotating db creds in SQLAlchemy v1, I've confirmed it no longer works in SQLAlchemy 2.0 so I'll remove it

2024-05-21 23:48 UTC, CamiloEVelasco commented on tests/conftest.py
> +    def restart_savepoint(sess2: Session, trans: Transaction) -> None:
All this does is nuke the test db at the end of each test xD

2024-05-23 14:09 UTC, merged